version: '3.4'

services:
  db:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    volumes:
        - '/var/opt/mssql'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 5671:5671
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  coinorderapi:
    image: ${DOCKER_REGISTRY-}coinorderapi
    build:
      context: .
      dockerfile: CoinOrderApi/Dockerfile
    depends_on:
        - db
        - rabbitmq
    environment:
      RabbitUrl: rabbitmq
      DbServer: "db"
      DbPort: "1433"
      DbUser: "SA"
      Password: "Secret1234"
      Database: "OrderAppDb"
